### ISSUE TITLE
Event on row reorder initialisation

### ISSUE THREAD

**Issue by THemming** [DataTables/RowReorder#11]
Would you be open to the idea of adding a new configuration option for RowReorder that allows a callback to be specified that is called before reorder interaction is initialised?

We are using a patched version of the extension internally that does this but we would prefer this to be merged upstream if acceptable.

New option:

``` js
rowReorder: {
    preReorder: function preReorderCallback() {
        // Code to run before reorder is initialised
    }
}
```

This is called in the `mousedown` handler within the extension, if the option is defined in the configuration.

**Comment by THemming** [comment]
Things to work out include:

- Name of configuration option
- How to handle error thrown within the callback (try-catch)
- What should the callback signature be? Could it return anything to stop reordering?

I would be able to submit a pull request for this if you are willing to accept it (pending review).

**Comment by DataTables** [comment]
I'd prefer an event rather than a callback. That would then match the [`row-reorder` event](https://datatables.net/reference/event/row-reorder) (which doesn't have a callback either).

What's the use case for this? Are you binding and unbinding events? If so, I can see that this might indeed be useful and would be happy to take a PR with the event added.

**Comment by THemming** [comment]
I was worried that an event wouldn't work for our use case, but just tried it and it works fine. We are resetting some table state when row reordering is initialised so it's important that the callback gets called before row is cloned. The event handlers seem to get called immediately but I though they might get queued on the event loop.

I've named the event `row-reorder-preInit`. Does this seem ok? Also, what data should be passed to the event handlers? How about:
```js
{triggerRow: DataTables.Api} // DataTables.API with the selected row in the result set
```

**Comment by DataTables** [comment]
`pre-row-reorder` would probably be more consistent with the other events.

For the information being passed in perhaps as close as possible to the `row-reorder` event's `details` parameter would be good - this is probably as close as we can get:

* node - tr element
* position - row index

**Comment by THemming** [comment]
Thanks. I'll get a pull request together in the next couple of weeks for this.

**Comment by DataTables** [comment]
Sounds great - many thanks for looking into this and taking my suggestions onboard :-)

**Comment by s0By** [comment]
This event would be really needed. In my case I need to block last row from being reordered, it has to always remain there.

Or is there a way for me to achieve that now?

**Comment by timhemming-fico** [comment]
@DataTables The solution we discussed was to provide an event, so no way to stop the row-reorder from happening. Should we change this to be callback registration so that any one of the pre-row-reorder callbacks could stop it from taking effect?

**Comment by THemming** [comment]
Implemented this event in pull request #15.

**Comment by DataTables** [comment]
Forgot to close this when #15 was merged in.

**Comment by JSonnabend** [comment]
I'm getting object types for both node and index parameters.  Shouldn't index be an integer?

**Comment by DataTables** [comment]
What is in the object?
