### ISSUE TITLE
Drag drop animation improvement

### ISSUE THREAD

**Issue by NZ-Jaybird** [DataTables/RowReorder#16]
When dragging a row up or down and hovering over a row, it would look nicer if the destination row being hovered over was blank to clearly show that it's the destination row - this is how Trello does it and I find it much more intuitive.

**Comment by DataTables** [comment]
Hi,

This can be controlled using CSS. The element being moved can be addressed with `tr.dt-rowReorder-moving` - use that to make the text hidden / change background / outline whatever to suit your style.

**Comment by NZ-Jaybird** [comment]
I'm playing around with this now and getting some good results. Thanks so much for your help, I'll close the issue.
