### ISSUE TITLE
The package may have incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by sadeghbarati** [DataTables/RowReorder#27]
@AllanJard sorry for direct mention,

Title; There is no `.mjs` or `.min.mjs` file in "datatables.net-rowreorder".

```json
{
    "name": "datatables.net-rowreorder",
    "description": "RowReorder for DataTables",
    "main": "js/dataTables.rowReorder.js",
    "module": "js/dataTables.rowReorder.mjs",
    "types": "./types/types.d.ts",
    .
    .
}
````

**Comment by sadeghbarati** [comment]
I think [`npm usage`](https://datatables.net/download/npm) must be updated `esm` syntax

```ts
var $       = require( 'jquery' );
var dt      = require( 'datatables.net' )( window, $ );
var buttons = require( 'datatables.net-buttons' )( window, $ );
```

```ts
import $ from 'jquery'
import dt from 'datatables.net'
import buttons from 'datatables.net-buttons'


// I'm not sure this is correct or not 

dt(window, $) // Value of type 'Api<any>' is not callable. Did you mean to include 'new'?
// or
new dt(globalThis, $)
//
buttons(window, $) // Value of type 'DataTables<any>' is not callable. Did you mean to include 'new'?
//or
new buttons(window, $)
```

**Comment by sadeghbarati** [comment]
https://github.com/DataTables/Dist-DataTables-RowReorder/tree/master/js

**Comment by AllanJard** [comment]
Hi - thanks for flagging this up. I'm just working on it at the moment.

**Comment by AllanJard** [comment]
Hi - that's it fixed with the 1.3.1 release. I had an error in the build script for this extension which meant it didn't build the mjs files (or wrap the UDM files correctly either).

**Comment by sadeghbarati** [comment]
Thanks 👍 , just a request:

including a starter for DataTables  with [`vite`](https://vitejs.dev/), [`turbopack`](https://turbo.build/pack) or `webpack` (nowadays bundlers) would be appreciated

---

Allan, I checked all datatables extension and also core DataTables code in `node_modules`

Some packages are still `umd` 
- `jquery.dataTables.js`
- `dataTables.dateTime.js`
- `dataTables.searchBuilder.js`
- `dataTables.searchPanes.js`

**Comment by AllanJard** [comment]
Yes, starter packages are on the radar :)

Regarding the UMD files - the DataTables core file should have been released, but apparently wasn't yesterday. It has been in the last few minutes.

SearchBuilder and SearchPanes are releases I'm working on at this very moment (StateRestore as well). DateTime will be the final one :)

**Comment by sadeghbarati** [comment]
Thanks You
