### ISSUE TITLE
Table fails to scroll when dragging rows

### ISSUE THREAD

**Issue by techfuse12** [DataTables/RowReorder#6]
For whatever reason, I'm so far unable to get the table scroll along with the dragged row. Here's a fiddle - https://jsfiddle.net/8zpdc0mt/

btw, although I'm using a scrollbar plugin, the same behavior occurs without it as well. 

Thanks!

**Comment by DataTables** [comment]
Looks like this is a missing feature in RowReorder. It [currently only does window scrolling](https://github.com/DataTables/RowReorder/blob/master/js/dataTables.rowReorder.js#L415).

It should do DataTables scrolling as well - thanks for bringing this up.
