### ISSUE TITLE
Add Ajax Initialisation Example

### ISSUE THREAD

**Issue by manderson23** [DataTables/RowReorder#9]
I think it would be useful if there was an example of using RowReorder with Ajax. It took a good bit of searching today for me to discover that I need to use `dataSrc` to reference the data to be used for ordering. 

I also came a across a few instances on the forum where this example could have helped.

**Comment by DataTables** [comment]
[There is an example here](https://editor.datatables.net/examples/extensions/rowReorder.html) but it is under the Editor examples. Its a good point that there should be one under the RowReorder examples - thanks.
